-- Reverse 000036.
DROP INDEX IF EXISTS idx_users_is_dpo;
ALTER TABLE users DROP COLUMN IF EXISTS is_dpo;
ALTER TABLE users DROP COLUMN IF EXISTS phone;
ALTER TABLE users DROP COLUMN IF EXISTS source;
